name: generate animation

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *"
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the main branch
  push:
    branches:
    - main
    
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Fetch contributions in 2024
      - name: Get contributions in 2024
        run: |
          ./fetch_contributions.sh ${{ github.repository_owner }}
        working-directory: ${{ github.workspace }}

      # Update snake animation SVG with contributions data
      - name: Update snake animation
        run: |
          ./update_snake_animation.sh input.svg contributions_2024.json output.svg
        working-directory: ${{ github.workspace }}

      # Generate snake game animation for 2024
      - name: Generate snake game animation
        run: |
          npx snk --input output.svg --output output/github-contribution-grid-snake.svg
          npx snk --input output.svg --output output/github-contribution-grid-snake-dark.svg --palette github-dark
        working-directory: ${{ github.workspace }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Push the content of <build_dir> to a branch
      - name: Push output files to the output branch
        uses: actions/checkout@v2
      - name: Commit files
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Update snake animation SVG with 2024 contributions"
      - name: Push changes
        uses: actions/github-script@0.10.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            git push
